### ISSUE TITLE
error gui

### ISSUE THREAD

**Issue by bakzhan22** [linguistica-uchicago/lxa5#21]
C:\Users\bakzhan>linguistica gui
Running the graphical user interface of Linguistica 5.2.1...
Traceback (most recent call last):
  File "c:\users\bakzhan\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\bakzhan\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\bakzhan\AppData\Local\Programs\Python\Python37\Scripts\linguistica.exe\__main__.py", line 7, in <module>
  File "c:\users\bakzhan\appdata\local\programs\python\python37\lib\site-packages\linguistica\__main__.py", line 46, in main
    gui_main()
  File "c:\users\bakzhan\appdata\local\programs\python\python37\lib\site-packages\linguistica\gui\__init__.py", line 63, in main
    app = QApplication(sys.argv)
TypeError: 'NoneType' object is not callable

**Comment by SaNuelson** [comment]
A bit late to the party but for any future visitors, I got this fixed by installing the `PyQtWebEngine` package.

**Comment by jacksonllee** [comment]
Apologies for the very late reply. This issue is now fixed in [linguistica v5.3.0](https://pypi.org/project/linguistica/5.3.0/). (Re-)installing from `pip install --upgrade "linguistica[gui]"` should now install `PyQtWebEngine` as well.
